project:
  type: book
  output-dir: docs

book:
  title: "R for Public Administration and Policy"
  author: "Keith E Lee Jr"
  date: "6/7/2024"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-chapter.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



